- Samples representing fecal, beach sediment/sand, lake water samples (at least 5 for each treatment, preference is 9)
- Targeted amplicon characterization (who is there)
- Comparative microbiome analyses (do microbial communities change over time/more or less similar to one another)
- Statistical significance (when do samples become statistically signficiant)
- Sourcetracking (https://github.com/biota/sourcetracker2) of fecal microbiomes compared to water microbiomes
